package codalyze.entity;

// Generated 04-Jun-2008 17:49:40 by Hibernate Tools 3.2.2.GA

/**
 * JavancssObjects generated by hbm2java
 */
public class JavancssObjects implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer ncss;
	private Integer functions;
	private Integer classes;
	private Integer javadocs;
	private int importId;

	public JavancssObjects() {
	}

	public JavancssObjects(int importId) {
		this.importId = importId;
	}

	public JavancssObjects(String name, Integer ncss, Integer functions,
			Integer classes, Integer javadocs, int importId) {
		this.name = name;
		this.ncss = ncss;
		this.functions = functions;
		this.classes = classes;
		this.javadocs = javadocs;
		this.importId = importId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getNcss() {
		return this.ncss;
	}

	public void setNcss(Integer ncss) {
		this.ncss = ncss;
	}

	public Integer getFunctions() {
		return this.functions;
	}

	public void setFunctions(Integer functions) {
		this.functions = functions;
	}

	public Integer getClasses() {
		return this.classes;
	}

	public void setClasses(Integer classes) {
		this.classes = classes;
	}

	public Integer getJavadocs() {
		return this.javadocs;
	}

	public void setJavadocs(Integer javadocs) {
		this.javadocs = javadocs;
	}

	public int getImportId() {
		return this.importId;
	}

	public void setImportId(int importId) {
		this.importId = importId;
	}

}
