package codalyze.entity;

// Generated 04-Jun-2008 17:49:40 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * JavancssImports generated by hbm2java
 */
public class JavancssImports implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private Date date;
	private String metadata;

	public JavancssImports() {
	}

	public JavancssImports(Date date, String metadata) {
		this.date = date;
		this.metadata = metadata;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getMetadata() {
		return this.metadata;
	}

	public void setMetadata(String metadata) {
		this.metadata = metadata;
	}

}
