package codalyze.entity;

// Generated 04-Jun-2008 17:49:40 by Hibernate Tools 3.2.2.GA

/**
 * JavancssPackages generated by hbm2java
 */
public class JavancssPackages implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer classes;
	private Integer functions;
	private Integer ncss;
	private Integer javadocs;
	private Integer javadocLines;
	private Integer singleCommentLines;
	private Integer multiCommentLines;
	private int importId;

	public JavancssPackages() {
	}

	public JavancssPackages(int importId) {
		this.importId = importId;
	}

	public JavancssPackages(String name, Integer classes, Integer functions,
			Integer ncss, Integer javadocs, Integer javadocLines,
			Integer singleCommentLines, Integer multiCommentLines, int importId) {
		this.name = name;
		this.classes = classes;
		this.functions = functions;
		this.ncss = ncss;
		this.javadocs = javadocs;
		this.javadocLines = javadocLines;
		this.singleCommentLines = singleCommentLines;
		this.multiCommentLines = multiCommentLines;
		this.importId = importId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getClasses() {
		return this.classes;
	}

	public void setClasses(Integer classes) {
		this.classes = classes;
	}

	public Integer getFunctions() {
		return this.functions;
	}

	public void setFunctions(Integer functions) {
		this.functions = functions;
	}

	public Integer getNcss() {
		return this.ncss;
	}

	public void setNcss(Integer ncss) {
		this.ncss = ncss;
	}

	public Integer getJavadocs() {
		return this.javadocs;
	}

	public void setJavadocs(Integer javadocs) {
		this.javadocs = javadocs;
	}

	public Integer getJavadocLines() {
		return this.javadocLines;
	}

	public void setJavadocLines(Integer javadocLines) {
		this.javadocLines = javadocLines;
	}

	public Integer getSingleCommentLines() {
		return this.singleCommentLines;
	}

	public void setSingleCommentLines(Integer singleCommentLines) {
		this.singleCommentLines = singleCommentLines;
	}

	public Integer getMultiCommentLines() {
		return this.multiCommentLines;
	}

	public void setMultiCommentLines(Integer multiCommentLines) {
		this.multiCommentLines = multiCommentLines;
	}

	public int getImportId() {
		return this.importId;
	}

	public void setImportId(int importId) {
		this.importId = importId;
	}

}
