package codalyze.entity;

// Generated 04-Jun-2008 17:49:40 by Hibernate Tools 3.2.2.GA

/**
 * JavancssFunctions generated by hbm2java
 */
public class JavancssFunctions implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer ncss;
	private Integer ccn;
	private Integer javadocs;
	private int importId;

	public JavancssFunctions() {
	}

	public JavancssFunctions(int importId) {
		this.importId = importId;
	}

	public JavancssFunctions(String name, Integer ncss, Integer ccn,
			Integer javadocs, int importId) {
		this.name = name;
		this.ncss = ncss;
		this.ccn = ccn;
		this.javadocs = javadocs;
		this.importId = importId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getNcss() {
		return this.ncss;
	}

	public void setNcss(Integer ncss) {
		this.ncss = ncss;
	}

	public Integer getCcn() {
		return this.ccn;
	}

	public void setCcn(Integer ccn) {
		this.ccn = ccn;
	}

	public Integer getJavadocs() {
		return this.javadocs;
	}

	public void setJavadocs(Integer javadocs) {
		this.javadocs = javadocs;
	}

	public int getImportId() {
		return this.importId;
	}

	public void setImportId(int importId) {
		this.importId = importId;
	}

}
