package codalyze.entity;

// Generated 04-Jun-2008 17:49:40 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JavancssImports generated by hbm2java
 */
@Entity
@Table(name="javancss_imports")
public class JavancssImports implements java.io.Serializable {

	private Integer id;
	private Date date;
	private String metadata;

	
	public JavancssImports() {
	}
	
	public JavancssImports(Date date, String metadata) {
		this.date = date;
		this.metadata = metadata;
	}
	
	@Column(nullable=false)
	public Date getDate() {
		return this.date;
	}

	@Id @GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getId() {
		return this.id;
	}

	@Column(nullable=false)
	public String getMetadata() {
		return this.metadata;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setMetadata(String metadata) {
		this.metadata = metadata;
	}

}
